name: WSL CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check runner system
        run: |
          echo "===== runner info ====="
          echo "whoami:"
          whoami
          echo "pwd:"
          pwd
          echo "uname:"
          uname -a
          echo "proc version:"
          cat /proc/version
          echo "files:"
          ls -la

      - name: Run Python file
        run: |
          echo "===== python version ====="
          python3 --version
          echo "===== run hello.py ====="
          python3 .github/workflows/python/hello.py
